"use client";

import { useState } from "react";

export default function BulkProductImport() {
  const [csv, setCsv] = useState(""); const [preview, setPreview] = useState<string[]>([]); const [message, setMessage] = useState("");
  async function previewCsv() { const response = await fetch("/api/admin/products/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, commit: false }) }); const payload = await response.json() as { data?: { rows?: Array<Record<string, string>> }; error?: { message?: string; details?: string[] } }; if (!response.ok) { setMessage([payload.error?.message, ...(payload.error?.details ?? [])].filter(Boolean).join(" ")); return; } setPreview((payload.data?.rows ?? []).map((row) => `${row.sku} · ${row.name} · ${row.categorySlug}`)); setMessage(`${payload.data?.rows?.length ?? 0} rows validated. Review before importing.`); }
  async function commitCsv() { const response = await fetch("/api/admin/products/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, commit: true }) }); const payload = await response.json() as { data?: { created?: number }; error?: { message?: string } }; setMessage(response.ok ? `${payload.data?.created ?? 0} products imported as supplied.` : payload.error?.message ?? "Import failed"); if (response.ok) { setCsv(""); setPreview([]); } }
  return <section className="mt-6 rounded-xs border border-line bg-white p-5"><h2 className="font-serif text-2xl">Bulk CSV import</h2><p className="mt-1 text-sm text-ink-soft">Preview first. Required columns: sku, slug, name, categorySlug.</p><textarea className="mt-4 min-h-28 w-full border border-line p-3 font-mono text-xs" value={csv} onChange={(event) => setCsv(event.target.value)} placeholder="sku,slug,name,categorySlug,priceMode,basePrice,stockQuantity,status" /><div className="mt-3 flex flex-wrap gap-3"><button type="button" className="border border-line px-4 py-2 text-sm font-semibold" onClick={() => void previewCsv()} disabled={!csv.trim()}>Preview CSV</button><button type="button" className="bg-ink px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" onClick={() => void commitCsv()} disabled={!preview.length}>Commit import</button></div>{preview.length ? <ul className="mt-4 max-h-40 overflow-auto border-t border-line pt-3 text-xs text-muted">{preview.map((item) => <li key={item} className="py-1">{item}</li>)}</ul> : null}{message ? <p className="mt-3 text-sm text-ink-soft" role="status">{message}</p> : null}</section>;
}
