import type { BlogPost, CollectionEntry, Product, Testimonial } from "./types";

const imageBank = {
  hero: "/assets/vedant-hero.jpg",
  heroVideo: "/assets/vedant-hero-video.mp4",
  antique: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=85",
  goldNecklace: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1400&q=85",
  diamondRing: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=85",
  bangles: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1400&q=85",
  bracelet: "https://images.unsplash.com/photo-1615655096345-61a54750068d?auto=format&fit=crop&w=1400&q=85",
  earrings: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=85",
  pendant: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1400&q=85",
  bridal: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1400&q=85",
  temple: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1400&q=85",
  kundan: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?auto=format&fit=crop&w=1400&q=85",
} as const;

export const assets = {
  antiqueNecklace: imageBank.hero,
  goldNecklace: imageBank.goldNecklace,
  diamondRing: imageBank.diamondRing,
  goldBangles: imageBank.bangles,
  bracelet: imageBank.bracelet,
  earrings: imageBank.earrings,
  pendant: imageBank.pendant,
  bridalJewellery: imageBank.bridal,
  templeJewellery: imageBank.temple,
  kundanSet: imageBank.kundan,
  heroVideo: imageBank.heroVideo,
};

const baseCare = [
  "Store separately in a soft jewellery box.",
  "Avoid perfume, water, and harsh chemicals.",
  "Clean gently with a dry, soft cloth after use.",
];

const trustHighlights = ["BIS Hallmarked", "Premium Finish", "Insured Delivery", "Easy Exchange"];

export const products: Product[] = [
  {
    id: "VJ-AN-1001",
    slug: "royal-antique-necklace",
    name: "Royal Antique Necklace",
    category: "Necklaces",
    collection: "Heritage Antique",
    sku: "VJ-22K-AN-1001",
    price: 285000,
    offerPrice: 249000,
    discount: "13% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "22K Gold",
    weight: "46.8 g",
    stoneType: "Polki-inspired CZ",
    occasion: "Wedding, Festive",
    image: imageBank.hero,
    video: imageBank.heroVideo,
    images: [imageBank.hero, imageBank.antique, imageBank.goldNecklace, imageBank.temple],
    rating: 4.9,
    reviewsCount: 42,
    badge: "Best Seller",
    highlights: ["BIS Hallmarked", "22K Gold", "Handcrafted", "Wedding Collection"],
    description: "A regal antique necklace designed for grand celebrations, detailed with traditional motifs and a rich gold finish.",
    specs: { "Product Code": "VJ-AN-1001", Closure: "Adjustable dori", Finish: "Antique matte gold", "Ideal For": "Bridal and festive wear" },
    care: baseCare,
    reviews: [
      { name: "Priya Soni", rating: 5, comment: "The antique finish feels premium and perfect for bridal styling." },
      { name: "Meera Vyas", rating: 5, comment: "Beautiful detailing and very clear demo product information." },
    ],
  },
  {
    id: "VJ-BN-1002",
    slug: "maharani-bridal-necklace",
    name: "Maharani Bridal Necklace",
    category: "Bridal Jewellery",
    collection: "Maharani Bridal",
    sku: "VJ-22K-BN-1002",
    price: 395000,
    offerPrice: 349000,
    discount: "12% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Bridal Certificate",
    purity: "22K Gold",
    weight: "64.2 g",
    stoneType: "Kundan and CZ",
    occasion: "Wedding",
    image: imageBank.bridal,
    images: [imageBank.bridal, imageBank.kundan, imageBank.goldNecklace, imageBank.antique],
    rating: 4.8,
    reviewsCount: 36,
    badge: "Bridal Pick",
    highlights: ["BIS Hallmarked", "Kundan Detail", "Premium Bridal Finish", "Handcrafted"],
    description: "A dramatic bridal necklace with layered richness, designed to become the centrepiece of a wedding look.",
    specs: { "Product Code": "VJ-BN-1002", Closure: "Adjustable hook", Finish: "High polish", "Ideal For": "Wedding day" },
    care: baseCare,
    reviews: [{ name: "Nisha Rathore", rating: 5, comment: "Looks luxurious and client-ready." }],
  },
  {
    id: "VJ-DR-1003",
    slug: "celeste-diamond-ring",
    name: "Celeste Diamond Ring",
    category: "Diamond Rings",
    collection: "Celeste Diamonds",
    sku: "VJ-18K-DR-1003",
    price: 145000,
    offerPrice: 129000,
    discount: "11% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "IGI Demo Certified",
    purity: "18K Gold",
    weight: "5.4 g",
    stoneType: "Lab-grown Diamond",
    occasion: "Engagement, Gifting",
    image: imageBank.diamondRing,
    images: [imageBank.diamondRing, imageBank.pendant, imageBank.bracelet, imageBank.earrings],
    rating: 4.9,
    reviewsCount: 58,
    badge: "New Arrival",
    highlights: ["Certified Diamonds", "18K Gold", "Premium Setting", "Gift Ready"],
    description: "A refined solitaire-inspired diamond ring with a luminous centre and graceful everyday proportions.",
    specs: { "Product Code": "VJ-DR-1003", Setting: "Prong", Finish: "Mirror polish", "Ideal For": "Engagement" },
    care: baseCare,
    reviews: [{ name: "Aarav Jain", rating: 5, comment: "Elegant ring presentation and smooth shopping flow." }],
  },
  {
    id: "VJ-GB-1004",
    slug: "parampara-gold-bangles",
    name: "Parampara Gold Bangles",
    category: "Bangles",
    collection: "Parampara Gold",
    sku: "VJ-22K-GB-1004",
    price: 210000,
    offerPrice: 189000,
    discount: "10% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Gold Certificate",
    purity: "22K Gold",
    weight: "34.6 g",
    stoneType: "None",
    occasion: "Festive, Daily Wear",
    image: imageBank.bangles,
    images: [imageBank.bangles, imageBank.goldNecklace, imageBank.bracelet, imageBank.temple],
    rating: 4.7,
    reviewsCount: 31,
    badge: "Hallmarked",
    highlights: ["22K Gold", "BIS Hallmarked", "Classic Pair", "Smooth Finish"],
    description: "A timeless pair of gold bangles with a balanced traditional pattern and comfortable daily-wear profile.",
    specs: { "Product Code": "VJ-GB-1004", Size: "2.6", Finish: "Gloss gold", Quantity: "Pair" },
    care: baseCare,
    reviews: [{ name: "Ritu Sharma", rating: 5, comment: "The bangles look very premium on the shop page." }],
  },
  {
    id: "VJ-KS-1005",
    slug: "zoya-kundan-set",
    name: "Zoya Kundan Set",
    category: "Bridal Jewellery",
    collection: "Zoya Kundan",
    sku: "VJ-22K-KS-1005",
    price: 265000,
    offerPrice: 235000,
    discount: "11% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Kundan Certificate",
    purity: "22K Gold",
    weight: "42.1 g",
    stoneType: "Kundan",
    occasion: "Reception, Wedding",
    image: imageBank.kundan,
    images: [imageBank.kundan, imageBank.bridal, imageBank.antique, imageBank.earrings],
    rating: 4.8,
    reviewsCount: 27,
    badge: "Trending",
    highlights: ["Kundan Work", "Handcrafted", "Bridal Finish", "Premium Box"],
    description: "A luminous kundan set created for ceremonial styling, rich in texture and elegant in proportion.",
    specs: { "Product Code": "VJ-KS-1005", Includes: "Necklace and earrings", Finish: "Kundan polish", "Ideal For": "Reception" },
    care: baseCare,
    reviews: [{ name: "Kavya Mehta", rating: 5, comment: "A great bridal demo product." }],
  },
  {
    id: "VJ-TS-1006",
    slug: "temple-lakshmi-set",
    name: "Temple Lakshmi Set",
    category: "Necklaces",
    collection: "Temple Heritage",
    sku: "VJ-22K-TS-1006",
    price: 325000,
    offerPrice: 299000,
    discount: "8% OFF",
    availability: "Limited Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Temple Certificate",
    purity: "22K Gold",
    weight: "58.5 g",
    stoneType: "Ruby-tone CZ",
    occasion: "Festive, Bridal",
    image: imageBank.temple,
    images: [imageBank.temple, imageBank.antique, imageBank.goldNecklace, imageBank.bridal],
    rating: 4.9,
    reviewsCount: 33,
    badge: "Limited",
    highlights: ["Temple Motifs", "22K Gold", "BIS Hallmarked", "Heirloom Style"],
    description: "A heritage temple jewellery set with devotional motifs and a grand traditional profile.",
    specs: { "Product Code": "VJ-TS-1006", Motif: "Lakshmi", Finish: "Antique", "Ideal For": "Festive rituals" },
    care: baseCare,
    reviews: [{ name: "Bhavna Joshi", rating: 5, comment: "Feels very premium and heritage focused." }],
  },
  {
    id: "VJ-BR-1007",
    slug: "aurelia-gold-bracelet",
    name: "Aurelia Gold Bracelet",
    category: "Bracelets",
    collection: "Aurelia Everyday",
    sku: "VJ-18K-BR-1007",
    price: 86000,
    offerPrice: 76000,
    discount: "12% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Gold Certificate",
    purity: "18K Gold",
    weight: "12.8 g",
    stoneType: "None",
    occasion: "Daily Wear, Gifting",
    image: imageBank.bracelet,
    images: [imageBank.bracelet, imageBank.hero, imageBank.diamondRing, imageBank.pendant],
    rating: 4.6,
    reviewsCount: 24,
    badge: "Gift Pick",
    highlights: ["18K Gold", "Modern Link", "Lightweight", "Gift Ready"],
    description: "A polished link bracelet designed for refined everyday luxury.",
    specs: { "Product Code": "VJ-BR-1007", Length: "7 inch", Finish: "High polish", Closure: "Lobster lock" },
    care: baseCare,
    reviews: [{ name: "Amit Rathore", rating: 4, comment: "Clean and modern product card design." }],
  },
  {
    id: "VJ-ER-1008",
    slug: "heritage-gold-earrings",
    name: "Heritage Gold Earrings",
    category: "Earrings",
    collection: "Heritage Gold",
    sku: "VJ-22K-ER-1008",
    price: 72000,
    offerPrice: 64000,
    discount: "11% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Gold Certificate",
    purity: "22K Gold",
    weight: "10.9 g",
    stoneType: "None",
    occasion: "Festive, Gifting",
    image: imageBank.earrings,
    images: [imageBank.earrings, imageBank.kundan, imageBank.pendant, imageBank.goldNecklace],
    rating: 4.7,
    reviewsCount: 29,
    badge: "Popular",
    highlights: ["22K Gold", "BIS Hallmarked", "Festive Detail", "Comfort Fit"],
    description: "Elegant gold earrings with a festive silhouette and a warm traditional finish.",
    specs: { "Product Code": "VJ-ER-1008", Backing: "Push back", Finish: "Gloss", "Ideal For": "Saree and lehenga" },
    care: baseCare,
    reviews: [{ name: "Meera Vyas", rating: 5, comment: "Perfect for a premium jewellery demo." }],
  },
  {
    id: "VJ-PD-1009",
    slug: "classic-gold-pendant",
    name: "Classic Gold Pendant",
    category: "Pendants",
    collection: "Everyday Luxe",
    sku: "VJ-18K-PD-1009",
    price: 54000,
    offerPrice: 48000,
    discount: "11% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Gold Certificate",
    purity: "18K Gold",
    weight: "7.6 g",
    stoneType: "CZ",
    occasion: "Daily Wear, Gifting",
    image: imageBank.pendant,
    images: [imageBank.pendant, imageBank.diamondRing, imageBank.bracelet, imageBank.earrings],
    rating: 4.5,
    reviewsCount: 18,
    badge: "New",
    highlights: ["18K Gold", "Minimal Pendant", "Gift Ready", "Premium Finish"],
    description: "A versatile pendant with a modern profile and elegant shine for daily styling.",
    specs: { "Product Code": "VJ-PD-1009", Chain: "Not included", Finish: "Polished", "Ideal For": "Daily wear" },
    care: baseCare,
    reviews: [{ name: "Sonal Jain", rating: 4, comment: "Simple and beautiful." }],
  },
  {
    id: "VJ-GR-1010",
    slug: "navya-gold-ring",
    name: "Navya Gold Ring",
    category: "Gold Rings",
    collection: "Navya Gold",
    sku: "VJ-22K-GR-1010",
    price: 62000,
    offerPrice: 56000,
    discount: "10% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Gold Certificate",
    purity: "22K Gold",
    weight: "8.2 g",
    stoneType: "None",
    occasion: "Daily Wear",
    image: imageBank.goldNecklace,
    images: [imageBank.goldNecklace, imageBank.diamondRing, imageBank.pendant, imageBank.bracelet],
    rating: 4.6,
    reviewsCount: 16,
    badge: "Hallmarked",
    highlights: ["22K Gold", "BIS Hallmarked", "Comfort Fit", "Polished Finish"],
    description: "A graceful gold ring with a traditional-meets-modern form for effortless daily elegance.",
    specs: { "Product Code": "VJ-GR-1010", Size: "14", Finish: "Gloss", "Ideal For": "Daily wear" },
    care: baseCare,
    reviews: [{ name: "Rohan Bafna", rating: 5, comment: "Nice detail and clean product specs." }],
  },
  {
    id: "VJ-CH-1011",
    slug: "imperial-gold-chain",
    name: "Imperial Gold Chain",
    category: "Chains",
    collection: "Imperial Gold",
    sku: "VJ-22K-CH-1011",
    price: 118000,
    offerPrice: 104000,
    discount: "12% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Gold Certificate",
    purity: "22K Gold",
    weight: "20.4 g",
    stoneType: "None",
    occasion: "Daily Wear, Gifting",
    image: imageBank.antique,
    images: [imageBank.antique, imageBank.goldNecklace, imageBank.bracelet, imageBank.pendant],
    rating: 4.6,
    reviewsCount: 21,
    badge: "Classic",
    highlights: ["22K Gold", "BIS Hallmarked", "Secure Clasp", "Daily Wear"],
    description: "A refined gold chain with a substantial yet elegant profile for everyday styling.",
    specs: { "Product Code": "VJ-CH-1011", Length: "20 inch", Finish: "High polish", Closure: "S-hook" },
    care: baseCare,
    reviews: [{ name: "Puneet Soni", rating: 4, comment: "Looks premium and practical." }],
  },
  {
    id: "VJ-MS-1012",
    slug: "saubhagya-mangalsutra",
    name: "Saubhagya Mangalsutra",
    category: "Mangalsutra",
    collection: "Saubhagya",
    sku: "VJ-18K-MS-1012",
    price: 92000,
    offerPrice: 82000,
    discount: "11% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "18K Gold",
    weight: "15.7 g",
    stoneType: "Black beads and CZ",
    occasion: "Daily Wear, Wedding",
    image: imageBank.pendant,
    images: [imageBank.pendant, imageBank.goldNecklace, imageBank.earrings, imageBank.bracelet],
    rating: 4.8,
    reviewsCount: 34,
    badge: "Loved",
    highlights: ["18K Gold", "Black Beads", "Modern Pendant", "Daily Comfort"],
    description: "A graceful mangalsutra designed with a modern pendant and classic black bead detailing.",
    specs: { "Product Code": "VJ-MS-1012", Length: "18 inch", Finish: "Gloss", "Ideal For": "Daily wear" },
    care: baseCare,
    reviews: [{ name: "Neha Mehta", rating: 5, comment: "Elegant and modern." }],
  },
  {
    id: "VJ-DC-1013",
    slug: "aarya-diamond-chain",
    name: "Aarya Diamond Chain",
    category: "Chains",
    collection: "Celeste Diamonds",
    sku: "VJ-18K-DC-1013",
    price: 175000,
    offerPrice: 158000,
    discount: "10% OFF",
    availability: "Limited Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "IGI Demo Certified",
    purity: "18K Gold",
    weight: "18.3 g",
    stoneType: "Lab-grown Diamonds",
    occasion: "Party, Gifting",
    image: imageBank.diamondRing,
    images: [imageBank.diamondRing, imageBank.pendant, imageBank.earrings, imageBank.bracelet],
    rating: 4.9,
    reviewsCount: 19,
    badge: "Limited",
    highlights: ["Certified Diamonds", "18K Gold", "Luxury Finish", "Insured Delivery"],
    description: "A diamond-accented chain created for evening elegance and premium gifting.",
    specs: { "Product Code": "VJ-DC-1013", Length: "18 inch", Finish: "Diamond polish", "Ideal For": "Occasion wear" },
    care: baseCare,
    reviews: [{ name: "Isha Kapoor", rating: 5, comment: "Great luxury presentation." }],
  },
  {
    id: "VJ-BG-1014",
    slug: "brinda-bridal-bangles",
    name: "Brinda Bridal Bangles",
    category: "Bangles",
    collection: "Maharani Bridal",
    sku: "VJ-22K-BG-1014",
    price: 248000,
    offerPrice: 222000,
    discount: "10% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Bridal Certificate",
    purity: "22K Gold",
    weight: "40.9 g",
    stoneType: "Ruby-tone CZ",
    occasion: "Wedding",
    image: imageBank.bangles,
    images: [imageBank.bangles, imageBank.bridal, imageBank.temple, imageBank.kundan],
    rating: 4.8,
    reviewsCount: 25,
    badge: "Bridal",
    highlights: ["22K Gold", "Bridal Pair", "BIS Hallmarked", "Ruby-tone Accent"],
    description: "A bridal bangle pair with ornate detailing and festive richness.",
    specs: { "Product Code": "VJ-BG-1014", Size: "2.6", Quantity: "Pair", Finish: "Antique gloss" },
    care: baseCare,
    reviews: [{ name: "Tanvi Jain", rating: 5, comment: "A beautiful bridal collection item." }],
  },
  {
    id: "VJ-PE-1015",
    slug: "noor-pearl-earrings",
    name: "Noor Pearl Earrings",
    category: "Earrings",
    collection: "Noor Pearls",
    sku: "VJ-18K-PE-1015",
    price: 68000,
    offerPrice: 59000,
    discount: "13% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Pearl Certificate",
    purity: "18K Gold",
    weight: "9.4 g",
    stoneType: "Cultured Pearls",
    occasion: "Party, Gifting",
    image: imageBank.earrings,
    images: [imageBank.earrings, imageBank.pendant, imageBank.bracelet, imageBank.diamondRing],
    rating: 4.7,
    reviewsCount: 17,
    badge: "Elegant",
    highlights: ["Cultured Pearl", "18K Gold", "Gift Ready", "Premium Finish"],
    description: "Pearl earrings with a soft glow and refined gold setting for timeless styling.",
    specs: { "Product Code": "VJ-PE-1015", Backing: "Push back", Finish: "Pearl polish", "Ideal For": "Evening wear" },
    care: baseCare,
    reviews: [{ name: "Lavina Shah", rating: 5, comment: "Very elegant product styling." }],
  },
  {
    id: "VJ-AP-1016",
    slug: "amaya-antique-pendant",
    name: "Amaya Antique Pendant",
    category: "Pendants",
    collection: "Heritage Antique",
    sku: "VJ-22K-AP-1016",
    price: 78000,
    offerPrice: 69000,
    discount: "12% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "22K Gold",
    weight: "11.6 g",
    stoneType: "CZ",
    occasion: "Festive, Gifting",
    image: imageBank.temple,
    images: [imageBank.temple, imageBank.pendant, imageBank.antique, imageBank.earrings],
    rating: 4.6,
    reviewsCount: 14,
    badge: "Antique",
    highlights: ["22K Gold", "Antique Finish", "BIS Hallmarked", "Handcrafted"],
    description: "An antique pendant with heritage motifs, perfect for festive layering.",
    specs: { "Product Code": "VJ-AP-1016", Chain: "Not included", Finish: "Antique", "Ideal For": "Festive wear" },
    care: baseCare,
    reviews: [{ name: "Devika Soni", rating: 4, comment: "Good antique detailing." }],
  },
  {
    id: "VJ-TR-1017",
    slug: "trisha-trinity-ring",
    name: "Trisha Trinity Ring",
    category: "Gold Rings",
    collection: "Everyday Luxe",
    sku: "VJ-18K-TR-1017",
    price: 58000,
    offerPrice: 51000,
    discount: "12% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Gold Certificate",
    purity: "18K Gold",
    weight: "6.7 g",
    stoneType: "CZ",
    occasion: "Daily Wear, Gifting",
    image: imageBank.bracelet,
    images: [imageBank.bracelet, imageBank.diamondRing, imageBank.pendant, imageBank.earrings],
    rating: 4.5,
    reviewsCount: 13,
    badge: "Minimal",
    highlights: ["18K Gold", "Trinity Detail", "Comfort Fit", "Gift Ready"],
    description: "A sleek trinity-style gold ring with soft contours for everyday luxury.",
    specs: { "Product Code": "VJ-TR-1017", Size: "13", Finish: "Satin gloss", "Ideal For": "Daily wear" },
    care: baseCare,
    reviews: [{ name: "Kirti Bansal", rating: 4, comment: "Nice modern piece." }],
  },
  {
    id: "VJ-DB-1018",
    slug: "evana-diamond-bracelet",
    name: "Evana Diamond Bracelet",
    category: "Bracelets",
    collection: "Celeste Diamonds",
    sku: "VJ-18K-DB-1018",
    price: 188000,
    offerPrice: 169000,
    discount: "10% OFF",
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "IGI Demo Certified",
    purity: "18K Gold",
    weight: "16.2 g",
    stoneType: "Lab-grown Diamonds",
    occasion: "Party, Anniversary",
    image: imageBank.hero,
    video: imageBank.heroVideo,
    images: [imageBank.hero, imageBank.diamondRing, imageBank.bracelet, imageBank.pendant],
    rating: 4.9,
    reviewsCount: 38,
    badge: "Premium",
    highlights: ["Certified Diamonds", "18K Gold", "Luxury Bracelet", "Insured Delivery"],
    description: "A shimmering diamond bracelet made for refined evening styling and memorable gifting.",
    specs: { "Product Code": "VJ-DB-1018", Length: "7 inch", Finish: "Diamond polish", Closure: "Box clasp" },
    care: baseCare,
    reviews: [{ name: "Simran Kothari", rating: 5, comment: "The video hero makes this feel premium." }],
  },
];

export const categories: string[] = [
  "Gold Rings",
  "Diamond Rings",
  "Earrings",
  "Necklaces",
  "Chains",
  "Pendants",
  "Bracelets",
  "Bangles",
  "Mangalsutra",
  "Bridal Jewellery",
];

/**
 * Maps a catalogue category label to the path-based route that filters to it
 * (see `categoryFromPath` in App.tsx). Path-based routing, not `?category=`
 * query params, is what ShopPage/App.tsx actually understand — this map is
 * the single source of truth so category links never silently no-op again
 * (QA defects #1/#2, foundation rewrite).
 */
export const categoryToPath: Record<string, string> = {
  "Gold Rings": "/gold-jewellery",
  "Diamond Rings": "/diamond-jewellery",
  Earrings: "/earrings",
  Necklaces: "/necklaces",
  Chains: "/chains",
  Pendants: "/pendants",
  Bracelets: "/bracelets",
  Bangles: "/bangles",
  Mangalsutra: "/mangalsutra",
  "Bridal Jewellery": "/bridal-collection",
};

export const collections: CollectionEntry[] = [
  { title: "Heritage Antique", copy: "Statement classics inspired by royal Indian jewellery.", image: imageBank.antique },
  { title: "Celeste Diamonds", copy: "Certified sparkle for engagements, anniversaries and evening wear.", image: imageBank.diamondRing },
  { title: "Maharani Bridal", copy: "Grand bridal designs for wedding-day presence.", image: imageBank.bridal },
  { title: "Everyday Luxe", copy: "Lightweight pieces for refined daily styling.", image: imageBank.bracelet },
];

export const offers: string[] = [
  "Flat demo 10% off on selected diamond jewellery",
  "Complimentary appointment for bridal styling",
  "Free insured delivery on premium demo orders",
];

export const trustItems: string[] = [...trustHighlights, "Certified Diamonds", "Secure Demo Checkout"];

export const testimonials: Testimonial[] = [
  { name: "Priya Soni", role: "Bridal Client", quote: "PS Jewellers feels premium from the first screen. The product details are clear and trustworthy." },
  { name: "Amit Rathore", role: "Gold Buyer", quote: "The shop flow, filters and hallmark details make this demo look ready for a real jewellery showroom." },
  { name: "Meera Vyas", role: "Antique Jewellery Buyer", quote: "The antique and bridal collections have an elegant luxury feel without becoming cluttered." },
];

export const blogPosts: BlogPost[] = [
  { title: "How to choose BIS hallmarked gold jewellery", date: "Buyer Guide", image: imageBank.bangles },
  { title: "Bridal jewellery styling for royal weddings", date: "Bridal Notes", image: imageBank.bridal },
  { title: "Diamond certification explained simply", date: "Diamond Guide", image: imageBank.diamondRing },
];

export function formatPrice(value: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}
