import type { BlogPost, CollectionEntry, Product, Testimonial } from "./types";

const managedAsset = (path: string) => {
  const publicBase = process.env.NEXT_PUBLIC_R2_PUBLIC_URL?.replace(/\/$/, "");
  if (!publicBase) return path;
  const relativePath = path.replace(/^\/assets\//, "");
  return `${publicBase}/site/bundled/${relativePath.split("/").map(encodeURIComponent).join("/")}`;
};

const imageBank = {
  hero: managedAsset("/assets/ps-hero.jpg"),
  heroVideo: managedAsset("/assets/ps-hero-video.mp4"),
  // Decorative imagery now uses real PS Jewellers photography rather than stock.
  antique: managedAsset("/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-1.jpg"),
  goldNecklace: managedAsset("/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra-1.jpg"),
  diamondRing: managedAsset("/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-1.jpg"),
  bangles: managedAsset("/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-1.jpg"),
  bracelet: managedAsset("/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-1.jpg"),
  earrings: managedAsset("/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-1.jpg"),
  pendant: managedAsset("/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-1.jpg"),
  bridal: managedAsset("/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-1.jpg"),
  temple: managedAsset("/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-1.jpg"),
  kundan: managedAsset("/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-1.jpg"),
  anklets: managedAsset("/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-1.jpg"),
  nath: managedAsset("/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-1.jpg"),
} as const;

export const assets = {
  antiqueNecklace: imageBank.hero,
  goldNecklace: imageBank.goldNecklace,
  diamondRing: imageBank.diamondRing,
  goldBangles: imageBank.bangles,
  bracelet: imageBank.bracelet,
  earrings: imageBank.earrings,
  pendant: imageBank.pendant,
  bridalJewellery: imageBank.bridal,
  templeJewellery: imageBank.temple,
  kundanSet: imageBank.kundan,
  anklets: imageBank.anklets,
  nath: imageBank.nath,
  heroVideo: imageBank.heroVideo,
};

const baseCare = [
  "Store separately in a soft jewellery box.",
  "Avoid perfume, water, and harsh chemicals.",
  "Clean gently with a dry, soft cloth after use.",
];

// Claims shown site-wide, so each must be true of the whole catalogue.
// "BIS Hallmarked" was previously applied to sterling silver pieces, which
// are not BIS hallmarked gold; the gold-specific claim now lives on the
// individual product records instead.
const trustHighlights = ["Hallmarked Gold", "925 Sterling Silver", "Certified Diamonds", "Lifetime Exchange"];

const productSeed: Product[] = [
  // ---------------------------------------------------------------------------
  // PS Jewellers catalogue. Every record below is real client inventory from the
  // July 2026 photoshoot, with names, product codes and weights taken from the
  // supplied spec sheets. The earlier placeholder records (stock photography and
  // invented pricing) were removed on 2026-07-25.
  // ---------------------------------------------------------------------------
  {
    id: "PSJ-ER-2001",
    slug: "gold-greek-square-diamond-top-earrings",
    name: "Regalia Greek-Key Diamond Tops",
    category: "Earrings",
    jewelleryCategory: "gold",
    isNewArrival: true,
    publishedAt: "2026-07-20T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-22K-ER-2001",
    price: 40400,
    offerPrice: 38300,
    discount: "5% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "22K Gold",
    weight: "4.840 g",
    stoneType: "Brilliant-cut CZ",
    occasion: "Party, Festive, Gifting",
    image: "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-1.jpg",
    video: "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings.mp4",
    images: [
      "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-1.jpg",
      "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-2.jpg",
      "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-3.jpg",
      "/assets/products/gold-greek-square-diamond-top-earrings/gold-greek-square-diamond-top-earrings-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "New Arrival",
    tags: ["Earrings", "Tops", "Studs", "Drop Earrings", "Gold Earrings", "22K Gold", "Greek Key", "Meander", "Square Earrings", "CZ", "Diamond Tops", "Party Wear", "Festive", "Gifting", "Kaan", "Tops for Women"],
    highlights: ["22K BIS Hallmarked Gold", "Greek-key meander border", "Secure screw-back lock", "Lightweight 4.840 g pair"],
    description: "A square drop top framed by a hand-finished Greek-key border, centred on a brilliant-cut stone and crowned with a floral cluster. Light enough for all-day wear, detailed enough for an occasion.",
    specs: { "Product Code": "PSJ-ER-2001", "Gross Weight": "4.910 g", "Net Weight": "4.840 g", Quantity: "Pair (2 pieces)", Closure: "Screw-back lock", Finish: "High-polish yellow gold" },
    care: baseCare,
    reviews: [],
  },
  {
    id: "PSJ-BN-2002",
    slug: "dual-tone-diamond-cut-gold-bangles",
    name: "Dual-Tone Diamond-Cut Gold Bangles",
    category: "Bangles",
    jewelleryCategory: "gold",
    isNewArrival: false,
    publishedAt: "2026-07-17T00:00:00.000Z",
    collection: "Maharani Bridal",
    sku: "PSJ-22K-BN-2002",
    price: 268300,
    offerPrice: 254500,
    discount: "5% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "22K Gold",
    weight: "32.130 g",
    stoneType: "None",
    occasion: "Wedding, Bridal, Festive, Party, Traditional",
    image: "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-1.jpg",
    video: "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles.mp4",
    images: [
      "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-1.jpg",
      "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-2.jpg",
      "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-3.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Best Seller",
    tags: ["Bangles", "Kada", "Gold Bangles", "22K Gold", "Dual Tone", "Two Tone", "Diamond Cut", "Twisted", "Set of 2", "Bridal", "Wedding", "Festive", "Traditional", "Churi", "Bangle Set"],
    highlights: ["Crafted from authentic 22K gold", "Dual-tone gold and silver finish", "Diamond-cut twisted design", "Set of 2 bangles"],
    description: "A pair of 22K dual-tone bangles worked in a twisted diamond-cut pattern, alternating yellow gold with a bright rhodium-toned band. Built for weddings, festive days and traditional ceremonies, and comfortable enough for extended wear.",
    specs: { "Product Code": "PSJ-BN-2002", "Product Type": "Designer Bangles", Quantity: "Set of 2 bangles", Design: "Twisted diamond-cut pattern", Finish: "Dual-tone (gold and silver)", "Gross Weight": "32.600 g", "Net Gold Weight": "32.130 g" },
    care: [
      "Store separately in a soft jewellery pouch or box.",
      "Avoid exposure to perfumes, chemicals and harsh cleaning agents.",
      "Clean gently with a soft microfibre or jewellery polishing cloth.",
      "Handle carefully to preserve the polished finish.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-MS-2003",
    slug: "floral-diamond-gold-mangalsutra",
    name: "Elegant Gold Mangalsutra with Floral Pendant",
    category: "Mangalsutra",
    jewelleryCategory: "gold",
    isNewArrival: false,
    publishedAt: "2026-07-14T00:00:00.000Z",
    collection: "Everyday Luxe",
    sku: "PSJ-22K-MS-2003",
    price: 40700,
    offerPrice: 38600,
    discount: "5% OFF",
    availability: "In Stock",
    hallmark: "BIS 916 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "22K Gold",
    weight: "4.870 g",
    stoneType: "Brilliant-cut CZ",
    occasion: "Daily Wear, Wedding, Anniversary, Festival, Party",
    image: "/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra-1.jpg",
    video: "/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra.mp4",
    images: [
      "/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra-1.jpg",
      "/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra-2.jpg",
      "/assets/products/floral-diamond-gold-mangalsutra/floral-diamond-gold-mangalsutra-3.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Loved",
    tags: ["Mangalsutra", "Mangalsutra Chain", "Gold Mangalsutra", "Black Beads", "Nallapusalu", "Thali", "Floral Pendant", "22K Gold", "CZ", "Daily Wear", "Wedding", "Anniversary", "Festival", "Lightweight", "Short Mangalsutra"],
    highlights: ["Elegant floral-inspired pendant", "Traditional black bead chain", "Lightweight and comfortable", "High-polish gold finish"],
    description: "A delicate black-bead chain carrying a floral-inspired pendant set with brilliant-cut stones. Traditional in meaning, contemporary in scale, and light enough to wear every day.",
    specs: { "Product Code": "PSJ-MS-2003", "Product Type": "Mangalsutra", Design: "Floral pendant", "Chain Type": "Gold chain with black beads", Finish: "High polish", "Gross Weight": "4.870 g", "Ideal For": "Women" },
    care: [
      "Store in a soft jewellery pouch.",
      "Avoid contact with perfumes and chemicals.",
      "Clean with a soft microfibre cloth.",
      "Keep away from moisture when not in use.",
      "Store separately to avoid scratches.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-MT-2004",
    slug: "oxidised-silver-ruby-maang-tikka",
    name: "Royal Ruby Silver Boriya Maang Tika",
    category: "Maang Tikka",
    jewelleryCategory: "silver",
    isNewArrival: false,
    publishedAt: "2026-07-11T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-MT-2004",
    price: 1800,
    offerPrice: 1700,
    discount: "6% OFF",
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Sterling Silver",
    weight: "13.930 g",
    stoneType: "Ruby-coloured stones",
    occasion: "Bridal, Wedding, Festive, Navratri, Traditional",
    image: "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-1.jpg",
    video: "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka.mp4",
    images: [
      "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-1.jpg",
      "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-2.jpg",
      "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-3.jpg",
      "/assets/products/oxidised-silver-ruby-maang-tikka/oxidised-silver-ruby-maang-tikka-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Bridal Pick",
    tags: ["Maang Tikka", "Maang Teeka", "Mang Tika", "Boriya", "Borla", "Rakhdi", "Matha Patti", "Head Jewellery", "Oxidised Silver", "925 Silver", "Silver Jewellery", "Ruby", "Temple Jewellery", "Rajwadi", "Bridal", "Navratri", "Garba", "Festive"],
    highlights: ["925 sterling silver, oxidised finish", "Ruby-red and white stone setting", "Concentric mandala layout", "Adjustable chain and hook"],
    description: "Sterling silver worked into a captivating circular boriya motif and set with radiant ruby-coloured stones. Traditional Rajasthani craftsmanship, sized to sit gracefully against a centre parting.",
    specs: { "Product Code": "PSJ-MT-2004", "Product Type": "Boriya Maang Tika", Metal: "925 Sterling Silver", Weight: "13.930 g", Design: "Traditional circular motif", "Stone Type": "Ruby-coloured stones", Finish: "Oxidised silver", Style: "Ethnic and heritage" },
    care: [
      "Store in an airtight pouch to slow natural tarnishing.",
      "Keep away from perfume, water and cosmetics.",
      "Wipe with a dry cotton cloth after wear.",
      "Do not use silver dip on oxidised finishes, it strips the antique patina.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-ER-2005",
    slug: "oxidised-silver-ruby-jhumka-earrings",
    name: "Rajwadi Oxidised Silver Jhumka Earrings",
    category: "Earrings",
    jewelleryCategory: "silver",
    isNewArrival: false,
    publishedAt: "2026-07-08T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-ER-2005",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Oxidised Silver",
    weight: "Available on request",
    stoneType: "Ruby-red and white stones",
    occasion: "Festive, Navratri, Wedding, Traditional",
    image: "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-1.jpg",
    video: "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings.mp4",
    images: [
      "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-1.jpg",
      "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-2.jpg",
      "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-3.jpg",
      "/assets/products/oxidised-silver-ruby-jhumka-earrings/oxidised-silver-ruby-jhumka-earrings-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Trending",
    tags: ["Jhumka", "Jhumki", "Earrings", "Oxidised Earrings", "Silver Earrings", "Oxidised Silver", "925 Silver", "Silver Jewellery", "Ruby", "Floral Stud", "Ghungroo", "Temple Jewellery", "Rajwadi", "Navratri", "Garba", "Festive", "Traditional"],
    highlights: ["925 sterling silver, oxidised", "Ruby-red floral stud top", "Ghungroo bead fringe", "Push-back closure"],
    description: "A floral stud set with ruby-red stones opens into a domed jhumka edged with ghungroo beads. Traditional Rajwadi craft in oxidised 925 silver, sized to move with you through a long festive evening.",
    specs: { "Product Code": "PSJ-ER-2005", "Product Type": "Jhumka Earrings", Metal: "925 Sterling Silver", Finish: "Antique oxidised", Design: "Floral stud with domed jhumka", Closure: "Push back" },
    care: [
      "Store in an airtight pouch to slow natural tarnishing.",
      "Keep away from perfume, water and cosmetics.",
      "Wipe with a dry cotton cloth after wear.",
      "Do not use silver dip on oxidised finishes, it strips the antique patina.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-NK-2006",
    slug: "oxidised-silver-peacock-long-haar",
    name: "Mayura Oxidised Silver Long Haar",
    category: "Necklaces",
    jewelleryCategory: "silver",
    isNewArrival: false,
    publishedAt: "2026-07-05T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-NK-2006",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Oxidised Silver",
    weight: "Available on request",
    stoneType: "Ruby-red stones",
    occasion: "Bridal, Wedding, Festive, Traditional",
    image: "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-1.jpg",
    video: "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar.mp4",
    images: [
      "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-1.jpg",
      "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-2.jpg",
      "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-3.jpg",
      "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Premium",
    tags: ["Long Haar", "Haar", "Rani Haar", "Necklace", "Silver Necklace", "Oxidised Necklace", "Oxidised Silver", "925 Silver", "Silver Jewellery", "Peacock", "Mayura", "Temple Jewellery", "Rajwadi", "Ghungroo", "Maroon Beads", "Bridal", "Festive", "Traditional"],
    highlights: ["925 sterling silver, oxidised", "Twin peacock motifs", "Multi-strand maroon bead cords", "Ghungroo drop fringe"],
    description: "A layered long haar strung on maroon bead cords, gathering into twin peacocks that flank a ruby-set medallion above a filigree panel and ghungroo fringe. Statement scale, built for bridal and heavy festive wear.",
    specs: { "Product Code": "PSJ-NK-2006", "Product Type": "Long Haar", Metal: "925 Sterling Silver", Finish: "Antique oxidised", Design: "Peacock motif with filigree panel", Fastening: "Adjustable dori" },
    care: [
      "Store in an airtight pouch to slow natural tarnishing.",
      "Keep away from perfume, water and cosmetics.",
      "Wipe with a dry cotton cloth after wear.",
      "Do not use silver dip on oxidised finishes, it strips the antique patina.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-NK-2007",
    slug: "oxidised-silver-temple-choker",
    name: "Royal Heritage Oxidised Silver Necklace",
    category: "Necklaces",
    jewelleryCategory: "silver",
    isNewArrival: false,
    publishedAt: "2026-07-02T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-NK-2007",
    price: 6300,
    offerPrice: 5900,
    discount: "6% OFF",
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Oxidised Silver",
    weight: "48.860 g",
    stoneType: "Red and green stone embellishments",
    occasion: "Bridal, Wedding, Festive, Traditional",
    image: "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-1.jpg",
    video: "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker.mp4",
    images: [
      "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-1.jpg",
      "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-2.jpg",
      "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-3.jpg",
      "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Hallmarked",
    tags: ["Choker", "Hasli", "Temple Choker", "Necklace", "Silver Necklace", "Oxidised Necklace", "Oxidised Silver", "925 Silver", "Silver Jewellery", "Temple Jewellery", "Rajwadi", "Star Motif", "Enamel", "Meenakari", "Ghungroo", "Bridal", "Festive", "Traditional"],
    highlights: ["925 sterling silver, oxidised", "Woven mesh collar", "Enamelled star centrepiece", "Adjustable chain extender"],
    description: "Intricate filigree work, delicate dangling accents and vibrant red and green stone embellishments across a broad woven collar. Traditional Indian craftsmanship at statement scale, finished in premium oxidised silver.",
    specs: { "Product Code": "ZAAD #7", "Product Type": "Oxidised silver necklace", Metal: "925 Sterling Silver", "Gross Weight": "48.860 g", "Net Weight": "48.860 g", Finish: "Premium oxidised", Design: "Traditional filigree with dangling elements", Fastening: "Hook with extender chain" },
    care: [
      "Store in an airtight pouch to slow natural tarnishing.",
      "Keep away from perfume, water and cosmetics.",
      "Wipe with a dry cotton cloth after wear.",
      "Do not use silver dip on oxidised finishes, it strips the antique patina.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-ER-2008",
    slug: "floral-diamond-stud-earrings",
    name: "Floral Diamond Stud Earrings",
    category: "Earrings",
    jewelleryCategory: "diamond",
    isNewArrival: true,
    publishedAt: "2026-06-29T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-18K-ER-2008",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "4.000 g",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Daily Wear, Office Wear, Wedding, Party",
    image: "/assets/products/floral-diamond-stud-earrings/floral-diamond-stud-earrings-1.jpg",
    images: [
      "/assets/products/floral-diamond-stud-earrings/floral-diamond-stud-earrings-1.jpg",
      "/assets/products/floral-diamond-stud-earrings/floral-diamond-stud-earrings-2.jpg",
      "/assets/products/floral-diamond-stud-earrings/floral-diamond-stud-earrings-3.jpg",
      "/assets/products/floral-diamond-stud-earrings/floral-diamond-stud-earrings-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "New Arrival",
    tags: ["Earrings", "Studs", "Tops", "Diamond Earrings", "Diamond Studs", "Floral", "Clover", "18K Gold", "Round Brilliant", "Daily Wear", "Office Wear", "Party Wear", "Gifting", "D Tops"],
    highlights: ["18K gold with round brilliant diamonds", "Delicate floral motif", "Secure push-back closure", "Light 4.000 g pair"],
    description: "Radiant gold set with round-cut diamonds in a delicate floral-inspired design. Refined enough for daily wear and bright enough for an occasion.",
    specs: { "Product Code": "D TOPS #1", Quantity: "1 pair (2 pieces)", "Gross Weight": "4.120 g", "Net Weight": "4.000 g", Design: "Floral motif", "Diamond Shape": "Round brilliant cut", Finish: "High polish", Style: "Classic luxury" },
    care: [
      "Store earrings in a soft jewellery pouch or separate box.",
      "Keep away from perfumes, lotions and harsh chemicals.",
      "Remove before swimming, bathing or exercising.",
      "Clean with a soft microfibre cloth after each use.",
      "Wash occasionally using mild soap and lukewarm water.",
      "Have the earrings professionally cleaned and inspected once a year.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-ER-2009",
    slug: "infinity-diamond-stud-earrings",
    name: "Elegant Infinity Diamond Stud Earrings",
    category: "Earrings",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-26T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-18K-ER-2009",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "3.090 g",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Daily Wear, Office Wear, Party, Gifting",
    image: "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings-1.jpg",
    video: "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings.mp4",
    images: [
      "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings-1.jpg",
      "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings-2.jpg",
      "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings-3.jpg",
      "/assets/products/infinity-diamond-stud-earrings/infinity-diamond-stud-earrings-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Trending",
    tags: ["Earrings", "Studs", "Tops", "Diamond Earrings", "Diamond Studs", "Infinity", "Knot", "18K Gold", "Round Brilliant", "Daily Wear", "Office Wear", "Party Wear", "Anniversary", "Gifting", "D Tops"],
    highlights: ["18K gold with round brilliant diamonds", "Intertwined infinity knot design", "Contemporary silhouette", "Light 3.090 g pair"],
    description: "An intertwined infinity-inspired design in lustrous gold set with diamonds — a knot that reads as eternal love, unity and quiet elegance.",
    specs: { "Product Code": "D TOPS #4", Quantity: "1 pair", "Gross Weight": "3.260 g", "Net Weight": "3.090 g", Design: "Infinity knot", "Diamond Shape": "Round brilliant cut", Style: "Contemporary luxury" },
    care: [
      "Store earrings separately in a soft jewellery pouch or box.",
      "Avoid direct contact with perfumes, lotions and chemicals.",
      "Remove before swimming, bathing or exercising.",
      "Clean gently with a soft microfibre cloth after use.",
      "Wash occasionally with mild soap and lukewarm water.",
      "Have the earrings professionally cleaned and inspected annually.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-NP-2010",
    slug: "diamond-nath-nose-ring",
    name: "Elegant Diamond Nath",
    category: "Nose Pin",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-23T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-18K-NP-2010",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "2.130 g",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Wedding, Bridal, Festive",
    image: "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-1.jpg",
    video: "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring.mp4",
    images: [
      "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-1.jpg",
      "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-2.jpg",
      "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-3.jpg",
      "/assets/products/diamond-nath-nose-ring/diamond-nath-nose-ring-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Bridal Pick",
    tags: ["Nose Pin", "Nath", "Nose Ring", "Nathni", "Laung", "Nose Stud", "Diamond Nath", "18K Gold", "Round Brilliant", "Bridal", "Wedding", "Festive", "Traditional", "Piercing Jewellery"],
    highlights: ["18K gold with round-cut diamonds", "Circular silhouette with floral accent", "Bridal heritage design", "Light 2.130 g"],
    description: "A graceful circular nath in gold set with round-cut diamonds and finished with a delicate floral accent — traditional heritage rendered at a modern, wearable scale.",
    specs: { "Product Code": "D NTH #4", Quantity: "1 piece", "Gross Weight": "2.250 g", "Net Weight": "2.130 g", Design: "Circular with floral accent", "Diamond Shape": "Round brilliant cut", "Ideal For": "Bridal and festive wear" },
    care: [
      "Store the nath in a separate soft jewellery pouch or box.",
      "Avoid contact with perfumes, makeup and harsh chemicals.",
      "Remove before sleeping, bathing or exercising.",
      "Clean gently with a soft microfibre cloth after use.",
      "Get the jewellery professionally cleaned and inspected annually.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-PD-2011",
    slug: "royal-teardrop-diamond-pendant",
    name: "Royal Teardrop Diamond Pendant",
    category: "Pendants",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-20T00:00:00.000Z",
    collection: "Heritage Antique",
    sku: "PSJ-18K-PD-2011",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "5.800 g",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Wedding, Festive, Anniversary, Gifting",
    image: "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-1.jpg",
    video: "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant.mp4",
    images: [
      "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-1.jpg",
      "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-2.jpg",
      "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-3.jpg",
      "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Premium",
    tags: ["Pendants", "Locket", "Diamond Pendant", "Teardrop", "Paisley", "Kairi", "Openwork", "Filigree", "18K Gold", "Round Brilliant", "Wedding", "Festive", "Anniversary", "Gifting"],
    highlights: ["18K gold with round brilliant diamonds", "Intricate openwork teardrop", "High-polish finish", "5.800 g net"],
    description: "An openwork teardrop worked in gold and set with diamonds that catch light through the pierced detail. A paisley-inspired silhouette built for celebrations and cherished moments.",
    specs: { "Product Code": "D LKT #74", Quantity: "1 piece", "Gross Weight": "5.940 g", "Net Weight": "5.800 g", Design: "Teardrop / paisley inspired", "Diamond Shape": "Round brilliant cut", Finish: "High polish", Style: "Traditional luxury" },
    care: [
      "Store the pendant in a separate jewellery box or soft pouch.",
      "Avoid direct contact with perfumes, hairsprays and cosmetics.",
      "Remove before bathing, swimming or exercising.",
      "Clean gently using a soft, lint-free cloth.",
      "Schedule professional cleaning and inspection annually.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-DR-2012",
    slug: "square-halo-diamond-ring",
    name: "Elegant Square Halo Diamond Ring",
    category: "Diamond Rings",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-17T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-18K-DR-2012",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "3.310 g",
    stoneType: "Round and Baguette Cut Diamond",
    occasion: "Engagement, Anniversary, Wedding, Gifting",
    image: "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-1.jpg",
    video: "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring.mp4",
    images: [
      "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-1.jpg",
      "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-2.jpg",
      "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-3.jpg",
      "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Best Seller",
    tags: ["Diamond Rings", "Rings", "Engagement Ring", "Halo Ring", "Square Halo", "Baguette", "18K Gold", "Round Brilliant", "Engagement", "Anniversary", "Wedding", "Gifting", "Angoothi"],
    highlights: ["18K gold, round and baguette diamonds", "Contemporary square halo", "Brilliance from every angle", "3.310 g net"],
    description: "A square halo set with round and baguette-cut diamonds, engineered so light returns from every facet. Built for engagements, anniversaries and everyday luxury alike.",
    specs: { "Product Code": "DR #145", "Gross Weight": "3.440 g", "Net Weight": "3.310 g", Design: "Square halo", "Diamond Shape": "Round and baguette cut", Finish: "High polish", Style: "Contemporary luxury" },
    care: [
      "Store the ring separately in a soft jewellery pouch or box.",
      "Avoid contact with perfumes, lotions and harsh chemicals.",
      "Remove before swimming, exercising or household chores.",
      "Clean gently with a soft microfibre cloth after use.",
      "Get the ring professionally inspected and cleaned once a year.",
      "Avoid dropping or exposing the ring to extreme temperatures.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-RM-2013",
    slug: "gold-diamond-halo-ring-mount",
    name: "18K Gold Diamond Halo Ring Mount",
    category: "Gold Rings",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-14T00:00:00.000Z",
    collection: "Celeste Diamonds",
    sku: "PSJ-18K-RM-2013",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "Made to Order",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Authenticity Certificate",
    purity: "18K Gold",
    weight: "Available on request",
    stoneType: "Pavé Diamond Halo (centre stone not included)",
    occasion: "Engagement, Wedding, Anniversary, Gifting",
    image: "/assets/products/gold-diamond-halo-ring-mount/gold-diamond-halo-ring-mount-1.jpg",
    video: "/assets/products/gold-diamond-halo-ring-mount/gold-diamond-halo-ring-mount.mp4",
    images: [
      "/assets/products/gold-diamond-halo-ring-mount/gold-diamond-halo-ring-mount-1.jpg",
      "/assets/products/gold-diamond-halo-ring-mount/gold-diamond-halo-ring-mount-2.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Made to Order",
    tags: ["Ring Mount", "Semi Mount", "Custom Ring", "Engagement Ring", "Halo Ring", "Gold Rings", "18K Gold", "Pave", "Open Gallery", "Bespoke", "Custom Jewellery", "Engagement", "Anniversary"],
    highlights: ["Premium 18K gold construction", "Pavé diamond halo", "Secure multi-prong setting", "Open gallery for extra brilliance"],
    description: "A halo mount built to hold a round centre stone of your choosing. The pavé-set halo adds brilliance while an open gallery lets light through from below — the foundation for a bespoke engagement ring.",
    specs: { "Jewellery Type": "Ring mount (centre stone not included)", Metal: "18K Gold", Style: "Halo", "Setting Type": "Multi-prong", "Centre Stone Shape": "Round", Finish: "High polish", "Lead Time": "Made to order" },
    care: [
      "Store the ring separately in a soft jewellery pouch or box.",
      "Avoid contact with perfumes, lotions and harsh chemicals.",
      "Remove before swimming, exercising or household chores.",
      "Clean gently with a soft microfibre cloth after use.",
      "Have the setting checked annually so the centre stone stays secure.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-BR-2014",
    slug: "diamond-mangalsutra-bracelet-trio",
    name: "Trio Diamond Mangalsutra Bracelet",
    category: "Bracelets",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-11T00:00:00.000Z",
    collection: "Everyday Luxe",
    sku: "PSJ-18K-BR-2014",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "Available on request",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Daily Wear, Office Wear, Anniversary, Gifting",
    image: "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-1.jpg",
    video: "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio.mp4",
    images: [
      "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-1.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-2.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-3.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Loved",
    tags: ["Bracelets", "Mangalsutra Bracelet", "Bracelet Mangalsutra", "Hand Mangalsutra", "Black Beads", "Nallapusalu", "Diamond Bracelet", "18K Gold", "Trio", "Three Stone", "Daily Wear", "Office Wear", "Anniversary", "Gifting", "Kada"],
    highlights: ["18K gold with black bead chain", "Three diamond stations", "Modern take on the mangalsutra", "Adjustable lobster clasp"],
    description: "The mangalsutra reimagined for the wrist — a black-bead chain punctuated by three diamond stations. Understated enough for the office, meaningful enough to never take off.",
    specs: { "Product Code": "PSJ-BR-2014", "Product Type": "Mangalsutra bracelet", Metal: "18K Gold", "Chain Type": "Gold chain with black beads", Design: "Three diamond stations", Closure: "Lobster clasp with extender" },
    care: [
      "Store in a soft jewellery pouch.",
      "Avoid contact with perfumes and chemicals.",
      "Clean with a soft microfibre cloth.",
      "Remove before swimming or exercising.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-BR-2015",
    slug: "diamond-mangalsutra-bracelet-solitaire",
    name: "Solitaire Diamond Mangalsutra Bracelet",
    category: "Bracelets",
    jewelleryCategory: "diamond",
    isNewArrival: false,
    publishedAt: "2026-06-08T00:00:00.000Z",
    collection: "Everyday Luxe",
    sku: "PSJ-18K-BR-2015",
    price: 0,
    offerPrice: 0,
    discount: "",
    priceOnRequest: true,
    availability: "In Stock",
    hallmark: "BIS 750 Hallmark",
    certification: "PS Diamond Certificate",
    purity: "18K Gold",
    weight: "Available on request",
    stoneType: "Round Brilliant Cut Diamond",
    occasion: "Daily Wear, Office Wear, Anniversary, Gifting",
    image: "/assets/products/diamond-mangalsutra-bracelet-solitaire/diamond-mangalsutra-bracelet-solitaire-1.jpg",
    images: [
      "/assets/products/diamond-mangalsutra-bracelet-solitaire/diamond-mangalsutra-bracelet-solitaire-1.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-solitaire/diamond-mangalsutra-bracelet-solitaire-2.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-solitaire/diamond-mangalsutra-bracelet-solitaire-3.jpg",
      "/assets/products/diamond-mangalsutra-bracelet-solitaire/diamond-mangalsutra-bracelet-solitaire-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Minimal",
    tags: ["Bracelets", "Mangalsutra Bracelet", "Bracelet Mangalsutra", "Hand Mangalsutra", "Black Beads", "Nallapusalu", "Diamond Bracelet", "Solitaire", "18K Gold", "Minimal", "Daily Wear", "Office Wear", "Anniversary", "Gifting"],
    highlights: ["18K gold with black bead chain", "Single halo-set centre", "Minimal everyday profile", "Adjustable lobster clasp"],
    description: "A single halo-set diamond centred on a fine black-bead chain. The quietest way to carry the mangalsutra tradition on your wrist.",
    specs: { "Product Code": "PSJ-BR-2015", "Product Type": "Mangalsutra bracelet", Metal: "18K Gold", "Chain Type": "Gold chain with black beads", Design: "Single halo centre", Closure: "Lobster clasp with extender" },
    care: [
      "Store in a soft jewellery pouch.",
      "Avoid contact with perfumes and chemicals.",
      "Clean with a soft microfibre cloth.",
      "Remove before swimming or exercising.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-AK-2016",
    slug: "leaf-pattern-silver-anklets",
    name: "Elegant Leaf Pattern Silver Anklets",
    category: "Anklets",
    jewelleryCategory: "silver",
    isNewArrival: true,
    publishedAt: "2026-06-05T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-AK-2016",
    price: 8300,
    offerPrice: 7900,
    discount: "5% OFF",
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Sterling Silver",
    weight: "64.576 g",
    stoneType: "None",
    occasion: "Daily Wear, Festive, Wedding, Traditional",
    image: "/assets/products/leaf-pattern-silver-anklets/leaf-pattern-silver-anklets-1.jpg",
    images: [
      "/assets/products/leaf-pattern-silver-anklets/leaf-pattern-silver-anklets-1.jpg",
      "/assets/products/leaf-pattern-silver-anklets/leaf-pattern-silver-anklets-2.jpg",
      "/assets/products/leaf-pattern-silver-anklets/leaf-pattern-silver-anklets-3.jpg",
      "/assets/products/leaf-pattern-silver-anklets/leaf-pattern-silver-anklets-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "New Arrival",
    tags: ["Anklets", "Payal", "Payal Set", "Anklet Pair", "Silver Anklets", "Silver Jewellery", "925 Silver", "Sterling Silver", "Leaf Motif", "Patti", "Jhanjhar", "Daily Wear", "Festive", "Wedding", "Traditional"],
    highlights: ["925 sterling silver", "Cascading leaf motif", "High-polish silver finish", "Sold as a pair, 64.576 g"],
    description: "Handcrafted sterling silver worked into a cascading leaf motif — a pattern read traditionally as prosperity and growth. Polished bright, and balanced between everyday and festive wear.",
    specs: { "Product Code": "PSJ-AK-2016", "Product Type": "Silver anklets (pair)", Metal: "925 Sterling Silver", "Approx. Weight": "64.576 g", Design: "Leaf motif", Finish: "High-polish silver", Style: "Traditional and contemporary" },
    care: [
      "Store the anklets in a soft pouch or airtight jewellery box.",
      "Avoid exposure to water, perfumes, lotions and household chemicals.",
      "Remove before bathing, swimming or exercising.",
      "Clean with a soft microfibre cloth after each use.",
      "Use a silver cleaning cloth occasionally to maintain shine.",
      "Store separately to avoid scratches and preserve the detailing.",
    ],
    reviews: [],
  },
  {
    id: "PSJ-AK-2017",
    slug: "royal-heritage-oxidised-silver-anklets",
    name: "Royal Heritage Oxidised Silver Anklets",
    category: "Anklets",
    jewelleryCategory: "silver",
    isNewArrival: false,
    publishedAt: "2026-06-02T00:00:00.000Z",
    collection: "Oxidised Heritage",
    sku: "PSJ-925-AK-2017",
    price: 11900,
    offerPrice: 11300,
    discount: "5% OFF",
    availability: "In Stock",
    hallmark: "925 Sterling Silver",
    certification: "PS Authenticity Certificate",
    purity: "925 Oxidised Silver",
    weight: "92.560 g",
    stoneType: "Multicolour enamel accents",
    occasion: "Wedding, Festive, Party, Traditional",
    image: "/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-1.jpg",
    images: [
      "/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-1.jpg",
      "/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-2.jpg",
      "/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-3.jpg",
      "/assets/products/royal-heritage-oxidised-silver-anklets/royal-heritage-oxidised-silver-anklets-4.jpg",
    ],
    rating: 0,
    reviewsCount: 0,
    badge: "Premium",
    tags: ["Anklets", "Payal", "Payal Set", "Anklet Pair", "Oxidised Anklets", "Silver Anklets", "Silver Jewellery", "925 Silver", "Sterling Silver", "Meenakari", "Enamel", "Jhanjhar", "Ghungroo", "Rajwadi", "Wedding", "Festive", "Traditional"],
    highlights: ["925 sterling silver, antique oxidised", "Multicolour enamel detailing", "Dangling ghungroo elements", "Sold as a pair, 92.560 g"],
    description: "Intricate handcrafted detailing with colourful enamel accents and dangling elements that move — and sound — with every step. Heritage Rajwadi craft in oxidised sterling silver.",
    specs: { "Product Code": "PSJ-AK-2017", "Product Type": "Silver anklets (pair)", Metal: "925 Sterling Silver", "Approx. Weight": "92.560 g", Finish: "Antique oxidised", "Accent Work": "Multicolour enamel", Style: "Ethnic and heritage" },
    care: [
      "Store the anklets in an airtight jewellery box or soft pouch.",
      "Avoid contact with water, perfumes, lotions and harsh chemicals.",
      "Remove before bathing, swimming or exercising.",
      "Clean gently with a soft, dry cloth after each use.",
      "Do not use silver polish, as it may strip the oxidised finish.",
      "Store separately to prevent tangling and scratches.",
    ],
    reviews: [],
  },
];

const managedProductAsset = (path: string) => path.startsWith("/assets/") ? managedAsset(path) : path;

export const products: Product[] = productSeed.map((product) => ({
  ...product,
  // Public policy: showroom pricing is confirmed privately for every piece.
  // Keep numeric values out of the client catalogue and show one consistent CTA.
  price: 0,
  offerPrice: 0,
  discount: "",
  priceOnRequest: true,
  image: managedProductAsset(product.image),
  video: product.video ? managedProductAsset(product.video) : product.video,
  images: product.images.map(managedProductAsset),
}));

export const categories: string[] = [
  "Recommended",
  "Gold Jewellery",
  "Silver Jewellery",
  "Diamond Jewellery",
  "Rings",
  "Earrings",
  "Necklaces",
];

/**
 * Maps a catalogue category label to the path-based route that filters to it
 * (see `categoryFromPath` in App.tsx). Path-based routing, not `?category=`
 * query params, is what ShopPage/App.tsx actually understand — this map is
 * the single source of truth so category links never silently no-op again
 * (QA defects #1/#2, foundation rewrite).
 */
export const categoryToPath: Record<string, string> = {
  Recommended: "/shop",
  "Gold Jewellery": "/gold-jewellery",
  "Silver Jewellery": "/silver-jewellery",
  "Diamond Jewellery": "/diamond-jewellery",
  Rings: "/rings",
  Earrings: "/earrings",
  Necklaces: "/necklaces",
};

const collectionSeed: CollectionEntry[] = [
  { title: "Heritage Antique", copy: "Statement silver in temple and Rajwadi traditions.", image: "/assets/products/oxidised-silver-peacock-long-haar/oxidised-silver-peacock-long-haar-1.jpg" },
  { title: "Celeste Diamonds", copy: "Diamond studs, pendants and rings in 18K gold.", image: "/assets/products/square-halo-diamond-ring/square-halo-diamond-ring-1.jpg" },
  { title: "Maharani Bridal", copy: "Hallmarked gold built for wedding-day presence.", image: "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-1.jpg" },
  { title: "Everyday Luxe", copy: "Lightweight pieces for refined daily styling.", image: "/assets/products/diamond-mangalsutra-bracelet-trio/diamond-mangalsutra-bracelet-trio-1.jpg" },
  { title: "Oxidised Heritage", copy: "Hand-finished 925 silver in temple and Rajwadi styles.", image: "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-1.jpg" },
];

export const collections: CollectionEntry[] = collectionSeed.map((collection) => ({ ...collection, image: managedProductAsset(collection.image) }));

export const offers: string[] = [
  "Complimentary bridal styling consultation",
  "Custom orders and made-to-order settings",
  "Exchange and buy-back on hallmarked gold",
];

export const trustItems: string[] = [...trustHighlights, "Showroom Assurance", "Insured Delivery"];

/**
 * Intentionally empty. The previous entries were invented quotes attributed to
 * named individuals. Publishing fabricated endorsements is a misleading-advert
 * risk under the Consumer Protection Act and the ASCI code. Populate only with
 * real, attributable customer feedback; the section hides itself while empty.
 */
export const testimonials: Testimonial[] = [];

const blogPostSeed: BlogPost[] = [
  { title: "How to choose BIS hallmarked gold jewellery", date: "Buyer Guide", image: "/assets/products/dual-tone-diamond-cut-gold-bangles/dual-tone-diamond-cut-gold-bangles-2.jpg" },
  { title: "Caring for oxidised silver jewellery", date: "Care Guide", image: "/assets/products/oxidised-silver-temple-choker/oxidised-silver-temple-choker-2.jpg" },
  { title: "Diamond certification explained simply", date: "Diamond Guide", image: "/assets/products/royal-teardrop-diamond-pendant/royal-teardrop-diamond-pendant-2.jpg" },
];

export const blogPosts: BlogPost[] = blogPostSeed.map((post) => ({ ...post, image: managedProductAsset(post.image) }));

export function formatPrice(value: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}
